In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np
import webbrowser
from ipywidgets import interact
import sympy as sp

## 107學年偏遠地區國中小名錄

In [2]:
df = pd.read_csv ("https://quality.data.gov.tw/dq_download_csv.php?nid=28582&md5_url=ec80153779022de861d1888232d72ca1")

In [4]:
df.head()

,縣市名稱,鄉鎮市區,學生等級,學校代碼,學校名稱,公/私立,地區屬性,地址,電話,網址,班級數,男教師數,女教師數,男學生數,女學生數,原住民學生比率,上學年男畢業生數,上學年女畢業生數
0,[01]新北市,八里區,國中,14527,市立八里國中,公立,偏遠,[249]新北市八里區荖阡坑路15號,(02)26102016,http://www.pljhs.ntpc.edu.tw,18,12,37,199,186,12.47,79,85
1,[01]新北市,石門區,國中,14537,市立石門國中,公立,偏遠,[253]新北市石門區中央路1之9號,(02)26381273,http://www.smjh.ntpc.edu.tw,6,2,14,45,55,0.00,18,18
2,[01]新北市,萬里區,國中,14539,市立萬里國中,公立,偏遠,[207]新北市萬里區獅頭路24號,(02)24922053,http://www.wljhs.ntpc.edu.tw,9,9,14,79,80,3.14,24,30
3,[01]新北市,坪林區,國中,14540,市立坪林國中,公立,特偏,[232]新北市坪林區國中路4號,(02)26656210,http://www.pljh.ntpc.edu.tw,7,8,14,61,48,0.00,27,18
4,[01]新北市,瑞芳區,國中,14544,市立瑞芳國中,公立,偏遠,[224]新北市瑞芳區三爪子坑路1號,(02)24972145,http://www.rfjh.ntpc.edu.tw,20,22,30,238,240,6.49,86,79

In [6]:
df.tail()

,縣市名稱,鄉鎮市區,學生等級,學校代碼,學校名稱,公/私立,地區屬性,地址,電話,網址,班級數,男教師數,女教師數,男學生數,女學生數,原住民學生比率,上學年男畢業生數,上學年女畢業生數
1100,[09]雲林縣,古坑鄉,附設國中,94308,縣立古坑華德福實驗高級中學,公立,特偏,[646]雲林縣古坑鄉荷苞村山峰17號,(05)5822075,http://tw.school.uschoolnet.com/?id=es00003779,6,0,0,43,38,1.23,12,12
1101,[13]屏東縣,枋寮鄉,附設國中,134321,縣立枋寮高中,公立,偏遠,[940]屏東縣枋寮鄉新龍村義民路3號,(08)8782095,http://www.flhs.ptc.edu.tw,25,0,0,336,335,23.40,138,130
1102,[13]屏東縣,來義鄉,附設國中,134334,縣立來義高中,公立,偏遠,[922]屏東縣來義鄉古樓村中正路147號,(08)7850086,http://www.lyhs.ptc.edu.tw,9,0,0,100,75,96.00,43,39
1103,[14]臺東縣,蘭嶼鄉,附設國中,144322,縣立蘭嶼高中,公立,特偏,[952]臺東縣蘭嶼鄉椰油村37號,(089)732016,http://www.layjh.ttct.edu.tw,6,0,0,48,41,100.00,17,13
1104,[15]花蓮縣,鳳林鎮,附設國中,154399,縣立南平中學,公立,偏遠,[975]花蓮縣鳳林鎮八德路62號,(03)8772586,http://www.nphs.hlc.edu.tw,0,0,0,0,0,0.00,0,0

In [7]:
df.describe()

,學校代碼,班級數,男教師數,女教師數,男學生數,女學生數,原住民學生比率,上學年男畢業生數,上學年女畢業生數
count,1105.000000,1105.000000,1105.000000,1105.000000,1105.000000,1105.000000,1105.000000,1105.000000,1105.000000
mean,120799.183710,7.268778,6.134842,9.466063,50.054299,45.247964,24.385557,13.381900,12.141176
std,116959.225159,4.448698,4.066132,6.758581,64.314042,60.319650,36.995125,21.807891,19.896334
min,14338.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,74744.000000,6.000000,4.000000,6.000000,20.000000,17.000000,0.000000,4.000000,3.000000
50%,104652.000000,6.000000,5.000000,8.000000,31.000000,28.000000,2.230000,6.000000,6.000000
75%,134751.000000,6.000000,7.000000,10.000000,51.000000,47.000000,46.880000,13.000000,11.000000
max,724608.000000,54.000000,44.000000,72.000000,654.000000,593.000000,100.000000,244.000000,222.000000

In [8]:
len(df)

1105

In [9]:
df.head(5)

,縣市名稱,鄉鎮市區,學生等級,學校代碼,學校名稱,公/私立,地區屬性,地址,電話,網址,班級數,男教師數,女教師數,男學生數,女學生數,原住民學生比率,上學年男畢業生數,上學年女畢業生數
0,[01]新北市,八里區,國中,14527,市立八里國中,公立,偏遠,[249]新北市八里區荖阡坑路15號,(02)26102016,http://www.pljhs.ntpc.edu.tw,18,12,37,199,186,12.47,79,85
1,[01]新北市,石門區,國中,14537,市立石門國中,公立,偏遠,[253]新北市石門區中央路1之9號,(02)26381273,http://www.smjh.ntpc.edu.tw,6,2,14,45,55,0.00,18,18
2,[01]新北市,萬里區,國中,14539,市立萬里國中,公立,偏遠,[207]新北市萬里區獅頭路24號,(02)24922053,http://www.wljhs.ntpc.edu.tw,9,9,14,79,80,3.14,24,30
3,[01]新北市,坪林區,國中,14540,市立坪林國中,公立,特偏,[232]新北市坪林區國中路4號,(02)26656210,http://www.pljh.ntpc.edu.tw,7,8,14,61,48,0.00,27,18
4,[01]新北市,瑞芳區,國中,14544,市立瑞芳國中,公立,偏遠,[224]新北市瑞芳區三爪子坑路1號,(02)24972145,http://www.rfjh.ntpc.edu.tw,20,22,30,238,240,6.49,86,79

In [14]:
df.corr().round(2)

          學校代碼   班級數  男教師數  女教師數  男學生數  女學生數  原住民學生比率  上學年男畢業生數  上學年女畢業生數
學校代碼      1.00  0.08  0.09  0.12  0.11  0.11    -0.05      0.05      0.05
班級數       0.08  1.00  0.76  0.86  0.92  0.92    -0.07      0.80      0.81
男教師數      0.09  0.76  1.00  0.69  0.75  0.75    -0.04      0.74      0.74
女教師數      0.12  0.86  0.69  1.00  0.84  0.84    -0.10      0.76      0.76
男學生數      0.11  0.92  0.75  0.84  1.00  0.98    -0.13      0.91      0.91
女學生數      0.11  0.92  0.75  0.84  0.98  1.00    -0.13      0.91      0.92
原住民學生比率  -0.05 -0.07 -0.04 -0.10 -0.13 -0.13     1.00     -0.13     -0.13
上學年男畢業生數  0.05  0.80  0.74  0.76  0.91  0.91    -0.13      1.00      0.96
上學年女畢業生數  0.05  0.81  0.74  0.76  0.91  0.92    -0.13      0.96      1.00